### ISSUE TITLE
Gradle Error

### ISSUE THREAD

**Issue by iCityWork** [hydra/pnpconvert#8]
### I am getting the following error when I try and build, any insight would be great. I am using Gradle 4.10 as you state in the READ.ME

*** What went wrong:
An exception occurred applying plugin request [id: 'com.gradle.enterprise', version: '3.4.1']
> Failed to apply plugin [id 'com.gradle.enterprise']
   > The Gradle Enterprise plugin must be applied to the settings (was applied to a project)
**

Thanks,
Gavin

**Comment by hydra** [comment]
Hey, please retry with latest master.  Gradle, groovy and other dependencies have been updated.  Create a new issue and reference this one if there's still issues.
